const emojis = [
    { emoji: "😀", name: "Happy" },
    { emoji: "🐶", name: "Woof" },
    { emoji: "🌮", name: "Mexicano" },
    { emoji: "❤️", name: "Lyy"},
    { emoji: "✨", name: "Sparkles"},
    { emoji: "✅", name: "Done"},
    { emoji: "🔥", name: "Fire"},
    { emoji: "💀", name: "'Dead'"},
    { emoji: "😂", name: " 'Lol' "},
    { emoji: "👀", name: "Suspicous"},
    { emoji: "🚀", name: "Up, up and away"},
    { emoji: "🌴", name: "Paradise"},
    { emoji: "🤔", name: "Hmmmm"},
    { emoji: "👍", name: "Cool..."},
    { emoji: "🫶", name: "Ily"},
    { emoji: "🎉", name: "Whoohoo"},
    { emoji: "☀️", name: "Sun"},
    { emoji: "📍", name: "Location"},
    { emoji: "😎", name: "Cool"},
    { emoji: "❌", name: "X"},
    { emoji: "😍", name: "In Love"},
    { emoji: "🫡", name: " 'Copy' "},
    { emoji: "😊", name: "Smiley"},
    { emoji: "🐝", name: "Bzzzz"},
    { emoji: "⛈️", name: " 'The old man is snoring' "},
    { emoji: "⛄", name: " 'Elsa...?' "},
    { emoji: "💍", name: "Will you marry me?"},
    { emoji: "🇸🇳", name: "Senegal"},
    { emoji: "🇲🇦", name: "Morocco"},
    { emoji: "🇦🇷", name: "Argentina"},
    { emoji: "🇺🇸", name: "USA"},
    { emoji: "🇨🇰", name: "Cook Islands"},
    { emoji: "🇮🇱", name: "Israel"},
    { emoji: "🇦🇺", name: "Australia"},
    { emoji: "🇫🇷", name: "France"},
    { emoji: "🇬🇧", name: "UK"},
    { emoji: "🇷🇴", name: "Romania"},
    { emoji: "🇧🇬", name: "Bulgaria"},
    { emoji: "🇧🇪", name: "Belgium"},
    { emoji: "🇪🇸", name: "Spain"},
    { emoji: "🇪🇺", name: "European Union"},
    { emoji: "🇳🇱", name: "Netherlands"},
    { emoji: "🇩🇰", name: "Denmark"},
    { emoji: "🇬🇷", name: "Greece"},
    { emoji: "🇷🇺", name: "Russia"},
    { emoji: "🇺🇦", name: "Ukraine"},
    { emoji: "🇻🇦", name: "Vatican City"},
    { emoji: "🇩🇪", name: "Germany"},
    { emoji: "🇧🇾", name: "Belarus"},
    { emoji: "🇦🇪", name: "UAE"},
    { emoji: "🇳🇿", name: "New Zealand"},
    { emoji: "🇨🇴", name: "Colombia"},
    { emoji: "🇿🇼", name: "Zimbabwe"},
    { emoji: "🇨🇦", name: "Canada"},
    { emoji: "🇨🇺", name: "Cuba"},
    { emoji: "🇩🇴", name: "Dominican Republic"},
    { emoji: "🇲🇶", name: "Martinique"},
    { emoji: "🇮🇳", name: "India"},
    { emoji: "🇰🇷", name: "South Korea"},
    { emoji: "🇨🇳", name: "China"},
    { emoji: "🇻🇳", name: "Vietnam"},
    { emoji: "🇻🇪", name: "Venezuela"},
    
    // Add more emoji objects
  ];
  
  module.exports = {
    emojis,
  };
  